default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_DATABASE') %>
  password: <%= ENV.fetch('MYSQL_ROOT_PASSWORD') %>
  host: 18.179.227.152

development:
  <<: *default
  database: app_name_development

test:
  <<: *default
  database: app_name_test

production:
  <<: *default
  database: mentuApp_production
  pool: 5
  username: root
  password: gabasu3710A*
  host: 18.179.227.152
  socket: /var/lib/mysql/mysql.sock
